### ISSUE TITLE
Signature from file

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/cover-letter-latex#14]
Usually, cover letters are also signed. We should add support so that author can easily add the signature from the file, e.g., a picture. 

What do you think, @KukovecRok ?

**Comment by KukovecRok** [comment]
Awesome idea, fixed in f15e7959d8085286766a7da794f102c02892f80a . Please check @firefly-cpp

**Comment by firefly-cpp** [comment]
Thanks very much!
